config/routes.rb
Rails.application.routes.draw do
  post '/register', to: 'fs_users#register', as: 'register'
  post '/login', to: 'fs_users#login', as: 'login'
  get '/logout', to: 'fs_users#logout', as: 'logout'
  get '/directory/:dir', to: 'fs_paths#directory', as: 'directory'
  post '/directory//upload', to: 'fs_paths#upload', as: 'upload'
  post '/directory/mkdir', to: 'fs_paths#mkdir', as: 'mkdir'
  post '/directory/delete/:dirname', to: 'fs_paths#deleteDir', as: 'deleteDir'
  post '/directory/delete/:filename/:filetype', to: 'fs_paths#deleteFile', as: 'deleteFile'

  root 'fs_users#new'

  

end

app/models/fs_path.rb
class FsPath < ActiveRecord::Base
  validates :path_name, uniqueness: true
end

app/models/fs_user.rb
class FsUser < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :fname, presence: true
  validates :lname, presence: true
  validates :pw_confirmation, presence: true
  validates :pw, confirmation: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fs_paths_controller.rb
class FsPathsController < ApplicationController
  attr_accessor :dir
  def directory
    @fs_user = FsUser.find(session[:id])
    session[:current_dir] = params[:dir]
  end
  
  def mkdir
    # we need a relative path to display to the user and an absolute one to actually read the files
    relDir = File.join(session[:current_dir].split("|"),params[:dirName])
    absDir = File.join(Rails.root,"public",relDir)
    
    fsPath = FsPath.new()
    fsPath.path_name = relDir
    fsPath.public = params[:rights] == "o"
    fsPath.user_id = session[:id]
    if fsPath.save
      Dir.mkdir(absDir,0700)
      redirect_to directory_path(session[:current_dir])
    else
      render plain: "error saving path "+fsPath.inspect
    end
  end
  
  def upload
    # instance of UploadedFile (or so...)
    uploadedFile = params[:file]
    
    # we need a relative path to display to the user and an absolute one to actually read the files
    relFilePath = File.join(session[:current_dir].split("|"),uploadedFile.original_filename)
    absFilePath = File.join(Rails.root,"public",relFilePath)
    fsPath = FsPath.new()
    fsPath.path_name = relFilePath
    fsPath.public = params[:rights] == "o"
    fsPath.user_id = session[:id]
    if fsPath.save
      # file is automatically closed at the end of the block
      File.open(absFilePath,"wb") do |file|
        file.write(uploadedFile.read)
      end
      redirect_to directory_path(session[:current_dir])
    else
      render plain: "error saving path "+fsPath.inspect
    end
  end
  
  def deleteDir
    relFilePath = File.join(session[:current_dir].split("|"),params[:dirname])
    doDelete(relFilePath)
    redirect_to directory_path(session[:current_dir])
  end
  
  def deleteFile
    relFilePath = File.join(session[:current_dir].split("|"),params[:filename]+"."+params[:filetype])
    doDelete(relFilePath)
    redirect_to directory_path(session[:current_dir])
  end
  
  private
    def doDelete(relFilePath)
      # we need a relative path to display to the user and an absolute one to actually read the files
      absFilePath = File.join(Rails.root,"public",relFilePath)
      # through the unique validation in the model, one path name only exits once, here raise exception if it doesn't
      fsPath = FsPath.find_by! path_name: relFilePath
      fsPath.destroy
      File.delete(absFilePath)
    end
end

app/controllers/fs_users_controller.rb
class FsUsersController < ApplicationController
  def new
    if (@fs_user == nil)
      @fs_user = FsUser.new
    end
    render "welcome/index"
  end
  
  def register
    @fs_user = FsUser.new(fs_user_params)
    @fs_user.save
    render "welcome/index"
    #redirect_to root_path
  end
  
  def login
    #puts "params: "+login_params
    #render plain: FsUser.where("email= ? and pw= ?",login_params[:email],login_params[:pw]).count
    @fs_user = FsUser.where("email= ? and pw= ?",login_params[:email],login_params[:pw]).first
    if(@fs_user != nil)
      session[:id] = @fs_user.id
      # redirect to the root path of the uploads using pipe instead of slash
      redirect_to directory_path("|uploads")
    else
      render plain: "could not find user"
    end
  end
  
  def logout
    session[:id] = nil
    redirect_to root_path
  end
  
  private
    def fs_user_params
      params.require(:fs_user).permit(:email, :fname, :lname, :pw, :pw_confirmation)
    end
    
    def login_params
      params.require(:fs_user).permit(:email, :pw)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fs_paths_helper.rb
module FsPathsHelper
  def getRelativePath(absolutePath)
    #absolutePath.sub Rails.root, "../.."
    absolutePath[Rails.root.to_s] = "../.."
    return absolutePath
  end
end

app/helpers/fs_users_helper.rb
module FsUsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/fs_paths/_directory_table.html.erb
<table id="directory">
	<thead>
		<tr><th>Name</th><th>Owner</th><th>Size</th><th>Open</th><th>Delete</th></tr>
	</thead>
	<tbody>
		<%
		#currentDir = File.join(Rails.root,"public",session[:current_dir].split('|'))
		# we need a relative path to lookup in the database and an absolute one to actually read the files
    		relCurrentDir = File.join(session[:current_dir].split("|"))
    		absCurrentDir = File.join(Rails.root,"public",relCurrentDir)
		%>
		<% Dir.foreach(absCurrentDir) do |filename| 
			if filename == "." or filename == ".." then next end #leave out "." and ".."
			relFilePath = File.join(relCurrentDir,filename)
			absFilePath = File.join(Rails.root,"public",relFilePath)
			FsPath.where("path_name = ? AND (user_id = ? OR public='t')",relFilePath,session[:id]).each do |fs_path| 
				fs_user = FsUser.find(fs_path.user_id)
				isDirectory = File.directory?(absFilePath)
				isMine = session[:id] == fs_path.user_id
			%>
				<tr>
					<td><%= relFilePath %></td>
					<td><%= fs_user.fname%> <%= fs_user.lname%></td>
					<% if isDirectory then%>
						<td>-</td>
						<% newDir = session[:current_dir]+"|"+filename%>
						<td><%= link_to newDir,directory_path(newDir)%></td>
						<td>
						<% if isMine then %>
							<%= link_to("delete TODO confirmation", deleteDir_path(filename), method: :post, confirm: "Are you sure?")%> 
						<% else %> - <%end%>
						</td>
					<% else %>
						<%
						fileparts = filename.split(".")
						file = File.open(absFilePath)
						size = (file.size/1024)
						%>
						<td><%= size.to_s+" KB" %></td>
						<td><%= link_to 'open file', relFilePath.html_safe, { target: '_blank' } %></td>
						<td>
						<% if isMine then %>
							<%= link_to("delete TODO confirmation", deleteFile_path(fileparts[0],fileparts[1]), method: :post, confirm: "Are you sure?")%> 
						<% else %> - <%end%>
						</td>
					<% end %>
					
				</tr>
			<% end %>
		<% end %>
			 
			
	<!-- <?php 				
		clearstatcache(); // cache leeren
		$files = scandir("." . $dir);
		$i = 0;
		$html = "";
		$zebra= "odd";
		foreach ($files as $f) {
			$i++;
			if ($i > 2) { // leave out "." and ".."
				// select registered path
				$path = "$dir/$f";
				$query = "SELECT 
							p.owner_user_id as owner_user_id,
							concat(u.user_fname,' ',u.user_lname) as owner_name
						  FROM
						    users u,
						    paths p
						  WHERE
						    p.path_name = '$path' AND
						  	u.user_id = p.owner_user_id AND								    
						    (p.owner_user_id = $user_id OR p.path_restriction = 'o')";
				if (! $result = mysql_query($query)) {
					die("error: " . mysql_error());
				}
				if ($row = mysql_fetch_array($result)) {
					// user is allowed to see this directory or path						
					$relativePath = ".$path";
					$ownerUserId = $row["owner_user_id"];
					$ownerName = $row["owner_name"];
					echo "<tr class='$zebra'>";
					if ($zebra == "odd") {
						$zebra = "even";
					} else {
						$zebra = "odd";
					}
					echo "<td>$f</td>";
					echo "<td>$ownerName</td>";
					
					if (is_dir($relativePath)) {
						echo "<td>-</td>";
						echo "<td> <a href='directory.php?dir=$path'>Open</td>";
						echo "<td>";
						if ($user_id == $ownerUserId) {
							// delete only allowed on users directories
							echo "TODO";
						}
						echo "</td>";
					}
					else {
						$size = round(filesize($relativePath) / 1024,2);
						echo "<td>$size KB</td>";
						echo "<td> <a href='$relativePath'>Download</td>";
						echo "<td>";
						if ($user_id == $ownerUserId) {
							// delete only allowed on users files
							echo "<a onclick='return confirmDelete()' href='delete.php?dir=$dir&file=$f'>Delete</a>";
						}
						echo "</td>";
					}			
					echo "</tr>";
				} 
			}
		}
	?> -->
	</tbody>
</table>

app/views/fs_paths/_mkdir.html.erb
<%= form_tag(action: :mkdir) do %>
  <%= label_tag "Name:"%> <%= text_field_tag "dirName" %><br/>
  <%= radio_button_tag(:rights, "o") %> <%= label_tag "visible for everyone" %><br/>
  <%= radio_button_tag(:rights, "r") %> <%= label_tag "visible just for me" %><br/>
  <%= submit_tag "Create dir" %>
<% end %>

app/views/fs_paths/_upload.html.erb
<!-- <form action="upload.php" method="post" enctype="multipart/form-data">
		<label for="file">Filename:</label>
		<input name="file" type="file" id="file"/></br>
		<input type="radio" name="rights" value="o" checked="checked"/> visible for everyone </br>
		<input type="radio" name="rights" value="r"/> visible just for me </br>
		<!--<?php echo "<input name='dir' type='hidden' id='dir' value='$dir'/>"; ?> 
		<br/>
		<input type="submit" name="submit" value="Hochladen"/>
	</form> -->
<%= form_tag({action: :upload}, multipart: true) do %>
  <%= file_field_tag 'file' %><br/>
  <%= radio_button_tag(:rights, "o") %> <%= label_tag "visible for everyone" %><br/>
  <%= radio_button_tag(:rights, "r") %> <%= label_tag "visible just for me"  %><br/>
  <%= submit_tag "Upload file" %>
<% end %>

app/views/fs_paths/directory.html.erb
<%= stylesheet_link_tag "style" %><h1>Fileserver</h1>
<nav>
	<%= link_to "Logout", logout_path %> | 
	<%
	concatDir = ""
	session[:current_dir].split("|").each do |parentDir| 
		next unless parentDir.length > 0
		concatDir += "|"+parentDir
		# don't put >> before root directory uploads
		if parentDir != "uploads" then %> &gt;&gt; <% end%>
		<%if concatDir.length < session[:current_dir].length then %>
			<%= link_to parentDir, directory_path(concatDir) %>
		<% else %>
			<span id="currentDir"><%= parentDir %></span>
		<% end %>
	<% end %>
	
	<!-- <?php 
	$prefDir = $dir;
	$i = -1;
	$prefDirs = array();
	while ($prefDir != "/uploads") {
		// cut off the part beginning with the last "/" of the directory
		$prefDir = substr($prefDir,0,strrpos($prefDir,"/",0));
		$i = $i + 1;
		$prefDirs[$i] = $prefDir;
	}
	for ($j = $i; $j >= 0; $j--) {
		if ($j != $i) {
			// no ">>" before root directory
			echo " &gt;&gt; ";
		}
		// write previous dir links in differenz order
		echo "<a href='directory.php?dir=$prefDirs[$j]'>$prefDirs[$j]</a>";
	}
	?> -->
</nav>
<!-- ><?php 
$writePermission = false;
if ($dir == "/uploads") {
	$writePermission = true;
} else {
	$query = "SELECT
				*
			  FROM
			    paths
			  WHERE
			    path_name = '$dir' AND
			    owner_user_id = $user_id";
	if (! $result = mysql_query($query)) {
		die("error: " . mysql_error());
	}
	if ($row = mysql_fetch_array($result)) {
		// this is the users directory						
		$writePermission = true;
	}
}

if ($writePermission) {
?>
-->
<div class="formgroup">
	<h2>Upload new file</h2>
	<%= render "fs_paths/upload" %>
</div>
<div class="formgroup">
	<h2>Create new directory</h2>
	<%= render "fs_paths/mkdir" %>
</div>
<?php 
	// end if: wirte permission
}
?>
<div class="formgroup">
	<!--<?php echo "<h2>Uploaded files: $dir</h2>";?>	-->
	<h2>Uploades files: <%= session[:current_dir] %></h2>
	<%= render "fs_paths/directory_table"%>
</div>
<div class="msg_info">
	<p>You are currently logged in as <%= @fs_user.fname%> <%= @fs_user.lname%></p>
</div>

app/views/fs_users/_login_form.html.erb
<%= form_for :fs_user, url: login_path, method: :post do |u| %>
  <p><%= u.label :email %><br/>
    <%= u.email_field :email %>
  </p>
  <p><%= u.label :pw %><br/>
    <%= u.password_field :pw %>
  </p>
  <p>
    <%= u.submit %>
  </p>
<% end %>

app/views/fs_users/_register_form.html.erb
<%= form_for :fs_user, url: register_path, method: :post do |u| %>
  <% if @fs_user.errors.any? %>
  <div class="msg_error">
    <p><%= pluralize(@fs_user.errors.count, "error") %> prohibited
      your registration:</p>
    <ul>
    <% @fs_user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% elsif @fs_user.new_record? == false%>
  <div class="msg_ok">
  	<p>Registration successful! Welcome, <%= @fs_user.fname%> <%= @fs_user.lname%></p>
  </div>
  <% end %>
  <p><%= u.label :email %><br/>
    <%= u.email_field :email %>
  </p>
  <p><%= u.label :fname %><br/>
    <%= u.text_field :fname %>
  </p>
  <p><%= u.label :lname %><br/>
    <%= u.text_field :lname %>
  </p>
  <p><%= u.label :pw %><br/>
    <%= u.password_field :pw %>
  </p>
  <p><%= u.label :pw %><br/>
    <%= u.password_field :pw_confirmation %>
  </p>
  <p>
    <%= u.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fileserver</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<%= stylesheet_link_tag "style" %>
<h1>Fileserver</h1>
<div class="formgroup">
	<h2>Register</h2>
	<%= render("fs_users/register_form")%>
</div>
<div class="formgroup">
	<h2>Login</h2>
	<%= render("fs_users/login_form")%>
</div>